### ISSUE TITLE
CocoaPods+Moya

### ISSUE THREAD

**Issue by EMidee66** [ashfurrow/Moya#101]
Hello Ash,

Can you help me with a problem?

When I installed my pods I used bundle exec pod install .. with cocoapods beta 1 on my gemfile. Today I put on the gemfile fastlane and now it's using cocoapods beta 2. I deleted fastlane gems and also cocoapods beta 2  + core but when I try bundle exec pod install it says: We couldn't find cocoapods core .. beta 2. Maybe one of the gems still needs beta 2 but I can't find which one. 
![screen shot 2015-02-22 at 4 00 37 pm](https://cloud.githubusercontent.com/assets/6751025/6318980/fd9cbb80-baab-11e4-85bf-cd7508c8e6f5.png)

Thank You!

**Comment by EMidee66** [comment]
Ok I fixed it. :) I see you guys at Artsy use beta 1. Are there any problems when you submit the app to the app store with beta 1?

**Comment by orta** [comment]
we don't need to submit to the app store, as it's an internal tool, I believe that beta 2 should have fixed the issues around deployment to app store.

**Comment by EMidee66** [comment]
Thank You Orta! :)
