### ISSUE TITLE
More of a "how do I", maybe a feature request.

### ISSUE THREAD

**Issue by colinta** [ashfurrow/Moya#102]
We are getting `Link: ... rel="prev"` URLs from our API that are used for pagination.  They return a full URL, and we need to use that URL in the subsequent request.

Since the URL includes `?query=params`, we are having a URL encoding issue.  Makes sense, though, since we are doing something outside the norm.  Is this even a situation that Moya wants to support?

In short, we are trying to come up with a way to bypass the usual URL encoding, and pass the URL and params in all the way down to `NSURLRequest`.

**Comment by colinta** [comment]
CC @rynbyjn and @steam - anything to add, fellas?

**Comment by steam** [comment]
@colinta we're currently parsing Link: into NSURLComponents and then reassembling the params in defaultParameters. Its not ideal though. I am curious how other Moya users handle this.

**Comment by ashfurrow** [comment]
Cool! @kylef has a cool repo. Maybe we could use it, or even borrow ideas from it: https://github.com/kylef/WebLinking.swift

**Comment by ashfurrow** [comment]
Could use the [representor pattern](https://github.com/the-hypermedia-project/charter#representor-pattern) too. Some closure that can return a(n optional?) new endpoint based on the previous response. This kind of thing would be really easy with the ReactiveCocoa extension: the signal for the initial request could emit another signal for a follow-up or something.

**Comment by steam** [comment]
Nice, we are using WebLinking.swift for the parsing. WebLinking gives us the ability to ask for "next" and "prev" which are super handy. The issue we're running into is that the links are already url encoded by the application server generating the "Link" in the response header. Just saw your representor pattern comment. We'll explore that internally. We're non-RAC so we'll need to come up with something without signals. Seems like a good idea though @ashfurrow. Thanks.

**Comment by ashfurrow** [comment]
This should be fixed [with this issue](https://github.com/ashfurrow/Moya/issues/74), which makes parameters like the ones you've discussed part of the target protocol.
