### ISSUE TITLE
filterSuccessfulStatusCodes

### ISSUE THREAD

**Issue by aschuch** [ashfurrow/Moya#103]
At the moment, [`RACSignal+Moya.swift`](https://github.com/ashfurrow/Moya/blob/190a180902919497de05ff4067d39ebcf4cfc96c/RACSignal%2BMoya.swift#L52) defines `200...299` as successful status codes.

I ran into an issue when dealing with cached responses (i.e. 3xx status codes) that would incorrectly be rejected.

Should we change the definition of successful to `200...399`?
I would be happy to open a pull request if needed, but want to start a discussion about this change first.

**Comment by ashfurrow** [comment]
Interesting! I think this comes down to a couple things:

- Do redirected responses contain a response body?
- Does Alamofire handle redirects transparently?

I believe the answer to the first question depends on your server/API. I don't know the answer to the second question. @kylef ?

Do you think having something like `filterSuccessfulStatusAndRedirectCodes` would be worth it?

**Comment by aschuch** [comment]
* I think that the server sends a response anyway, although it may not contain any actual data. However, it would still be possible to parse the response into a `MoyaResponse` object to e.g. get its `statusCode`.
* Based on [this PR](https://github.com/Alamofire/Alamofire/pull/350), Alamofire seems to be handling redirects transparently, but I have not had the time to further investigate.

Something like `filterSuccessfulStatusAndRedirectCodes` definitely makes sense, especially for backwards compatibility with any existing code using this library.

**Comment by ashfurrow** [comment]
Sounds good!
