### ISSUE TITLE
Difficulty installing with ReactiveCocoa and LlamaKit using the method described in your docs.

### ISSUE THREAD

**Issue by sebinsua** [ashfurrow/Moya#104]
[The version in your ReactiveCocoa podspec](https://github.com/ashfurrow/ReactiveCocoa/blob/podspec/ReactiveCocoa.podspec#L38) does not seem to match [the version defined in your LlamaKit repo](https://github.com/ashfurrow/LlamaKit/blob/rac_podspec/LlamaKit.podspec#L3).

On trying to install the two pods together I am getting this error message:
```
[!] Unable to satisfy the following requirements:

- `LlamaKit (from `https://github.com/AshFurrow/LlamaKit`, branch `rac_podspec`)` required by `Podfile`
- `LlamaKit (= 0.1.1)` required by `ReactiveCocoa (3.0.0-alpha.1)`
```

Any ideas?

**Comment by ashfurrow** [comment]
The ReactiveCocoa version requires a specific version of LlamaKit; you'll need to use the same version in your Podfile.

**Comment by sebinsua** [comment]
What I mean is that this happens when you follow the installation instructions in your README. :)

``
pod 'Moya', :git => "https://github.com/AshFurrow/Moya"

# Include the following only if you want to use ReactiveCocoa extensions with Moya
pod 'LlamaKit', :git => "https://github.com/AshFurrow/LlamaKit", :branch => "rac_podspec"
pod 'ReactiveCocoa', :git => "https://github.com/AshFurrow/ReactiveCocoa", :branch => "podspec"
pod 'Moya/Reactive', :git => "https://github.com/AshFurrow/Moya"
```

**Comment by ashfurrow** [comment]
Ah, apologies. The README looks out of date. Only include the pod names and not their :git components.

**Comment by ashfurrow** [comment]
I'll update the README soon.

**Comment by sebinsua** [comment]
Ah, alright. Thanks for the help. :)
