### ISSUE TITLE
Moya doesn't compile on XC 6.3 beta 4, Swift 1.2

### ISSUE THREAD

**Issue by te-chris** [ashfurrow/Moya#106]
I'm trying to get Moya going on a swift 1.2 XC 6.3 Beta 4 project and running into some compile errors.  Some were easy fixes (swift demanding that a method parameter be called with its parameter name on lines 166, 170, 174 of Moya.swift, adding the parameter name in satisfied the compiler), but one is stumping me somewhat:
```swift
/// Used for stubbing responses.
public enum EndpointSampleResponse {
    case Success(Int, NSData)
    case Error(Int?, NSError?, NSData?)
    case Closure(@autoclosure () -> EndpointSampleResponse)

    func evaluate() -> EndpointSampleResponse {
        switch self {
        case Success, Error: return self
        case Closure(let closure):
            return closure().evaluate()
        }
    }
}

```
The use of @autoclosure here raises a ``` '...Pods/Moya/Endpoint.swift:16:19: 'autoclosure' attribute is only allowed on parameters, not on enum cases'```

error.   I'm not familiar enough with swift yet to know what a the right thing to do in this situation is, though it looks like this discussion here covers it somewhat, at least I think so.  https://devforums.apple.com/message/1101244#1101244

**Comment by aschuch** [comment]
See changes in #107.

**Comment by ashfurrow** [comment]
Hey! These have been merged in. I updated the dependency on ReactiveCocoa on CocoaPods trunk. I don't have access to do so with Alamofire, our other dependency, so you need to have a Podfile that declares you're using their pre-release version *first*.

```rb
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'xcode-6.3'
pod 'Moya', :git => 'https://github.com/ashfurrow/Moya.git', :branch => 'swift-1.2'

# Or, if you're using ReactiveCocoa extensions...
pod 'Moya/Reactive', :git => 'https://github.com/ashfurrow/Moya.git', :branch => 'swift-1.2'
```

I just tried that on a test project and it seemed :+1: so feel free to re-open this issue if you're still experiencing problems and we'll work through it!

**Comment by te-chris** [comment]
Thanks! @ashfurrow great project, can't wait to get more familiar with it.

**Comment by ashfurrow** [comment]
@te-chris Glad to hear that! As always, don't hesitate to open an issue if you have a question, if something doesn't work the way you expect it to based on the documentation, etc.
