### ISSUE TITLE
Update to Support Latest Swift & Dependencies

### ISSUE THREAD

**Issue by skywinder** [ashfurrow/Moya#113]
Now it's strictly binded to Alamofire version `1.1.0` 
https://github.com/ashfurrow/Moya/blob/master/Moya.podspec#L23

But it's `1.2.1` version already released. Is there any reasons to stay with `1.1.0`?

**Comment by ashfurrow** [comment]
Hmm. The only reason I can think of is that Moya hasn't been updated for Swift 1.2 yet, but Alamofire has. Suggestions?

**Comment by skywinder** [comment]
@ashfurrow hmm, update it to 1.2? :wink:

**Comment by ashfurrow** [comment]
Haha yeah. I should get on that ... I'll rename the issue.

**Comment by ashfurrow** [comment]
Pretty busy for the next five or so days. Feel free to take a stab at it in the mean time ;)

**Comment by ashfurrow** [comment]
This is fixed as of https://github.com/ashfurrow/Moya/releases/tag/0.8.0 .

**Comment by skywinder** [comment]
Hooray! :+1:
