### ISSUE TITLE
Add more committers to Moya

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Moya#135]
I want other people to feel like they own Moya, too, so it survives in the long run.

What I'm looking for is people who can:

- Reply to questions.
- Help diagnose/fix issues people have.
- Help form a roadmap for future releases.

All when you have time and feel like it. It's not meant to be a burden.

> Don't ever feel bad for not contributing to open source. —@alloy

Thanks to @searls for the push to do this. 

If you're interested in helping out – when it's convenient for you – comment on this issue and I'll add you as a committer with push access.

/cc @colinta @orta @skywinder @garnett @aschuch @raphaelmor @powerje @process255 @powerje @neonichu @Thomvis @alcarvalho @joshuatbrown @SRandazzo @pietbrauer @juhagman @vandyshev @jspahrsummers @lipka @stephencelis

**Comment by steam** [comment]
Sounds great @ashfurrow, I'm in. I think @colinta is mentioning this but I have two github accounts, doh, and I use @steam for the most part these days (I am also @process255). If possible @steam would be a better github user to add.

Great work with Moya so far. We're loving it at Ello.

**Comment by colinta** [comment]
I'm in!  We had loved using Moya at @ello.  We're using, I *think*, all the features that Moya provides, and we'd like to not only keep abreast of changes, but help other people take advantage of it.

**Comment by ashfurrow** [comment]
Super awesome!

**Comment by neonichu** [comment]
I'm not actually using Moya, but I'd be up to help out with support for dependency managers :)

**Comment by SRandazzo** [comment]
That would be great! Still getting familiar with Moya but this will help push me along!

**Comment by aschuch** [comment]
Great idea, count me in.

**Comment by ashfurrow** [comment]
Awesome. @neonichu since you mentioned it, I've added you as an owner to the pod in CocoaPods trunk.

**Comment by alcarvalho** [comment]
I would love to help, too! I am still in the early stages of adopting it, but our new app's communication layer will be all using Moya. :+1:

**Comment by skywinder** [comment]
+1 :+1:

**Comment by ashfurrow** [comment]
Gonna call this done! Thanks for your help, everyone :cake:

**Comment by searls** [comment]
And for anyone looking for that "push" I gave Ash, [this is the talk](http://blog.testdouble.com/posts/2014-12-02-the-social-coding-contract.html) he's referencing.

**Comment by alloy** [comment]
@ashfurrow Btw another thing you can do, going forward, is that, while you can still oversee it all, give commit access to contributors early.

E.g. When they create a second PR that follows all design rules.

It worked great for CocoaPods, but your audience and mileage might vary.

**Comment by ashfurrow** [comment]
@ally I like it. As though adding more contributors should be a regularly part of open source. :bow:

**Comment by alloy** [comment]
I wouldn’t say _all_ open source, but if your goal is to have contributors, then yeah making them feel as owners hugely improves contribution. I’d also outline the rules for getting push access in e.g. your README, which might give people that extra push they need to contribute something they’d otherwise not feel motivated enough for.

**Comment by jcampbell05** [comment]
@ashfurrow I really like the message you wrote here, is it possible to use this as a template for a similar issue for my own project ? (Obviously tagging different users).

**Comment by orta** [comment]
You might want to conform to the Moya Contributing guidelines - which is still in a bit of flux, https://github.com/Moya/contributors/issues/6 but can provide a lot of the framework you're looking for

**Comment by ashfurrow** [comment]
Yeah, go for it 🎉 The guidelines Orta linked to are great, please let me know if I can help at all, and let me know how it goes!
