### ISSUE TITLE
Combine MoyaTarget and MoyaPath protocols

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Moya#136]
Does it make sense now that we're saying that `parameters` are on the target, and `path` is on the path, given that either property depends on the enum's associated values? 

/cc @chriseidhof

**Comment by colinta** [comment]
My immediate, gut response is yes, because they seem related and it's easier (conceptually, to a new Moya user) to implement just the one protocol. 

Is there ever a time when these protocols would be implemented by separate objects?

**Comment by chriseidhof** [comment]
I don't really understand the code base, so feel unqualified to comment on
this... But I'd be happy to have a look at this together at a computer
during the next days?

On Thu, Jun 11, 2015 at 9:01 PM, Colin T.A. Gray <notifications@github.com>
wrote:

> My immediate, gut response is yes, because they seem related and it's
> easier (conceptually, to a new Moya user) to implement just the one
> protocol.
>
> Is there ever a time when these protocols would be implemented by separate
> objects?
>
>
> > On Jun 11, 2015, at 8:35 PM, Ash Furrow <notifications@github.com>
> wrote:
> >
> > Does it make sense now that we're saying that parameters are on the
> target, and path is on the path, given that either property depends on the
> enum's associated values?
> >
> > /cc @chriseidhof
> >
> > ―
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ashfurrow/Moya/issues/136#issuecomment-111345814>.
>



-- 
Chris Eidhof
