### ISSUE TITLE
Make it easier to browse code on Github

### ISSUE THREAD

**Issue by aschuch** [ashfurrow/Moya#138]
At the moment, I find it hard to browse code on the Github repo.
I think we should consider adding a folder structure to make browsing Moya on Github a better experience.

I would keep everything the same but introduce a new `Moya` folder that contains all the relevant files.

```
- 📁Demo
- 📁docs
- 📁web
- 📁Moya
-- Endpoint.swift
-- Moya.swift
-- MoyaResponse.swift
-- 📁ReactiveCocoa
--- Moya+ReactiveCocoa.swift
--- RACSignal+Moya.swift
-- 📁RxSwift
--- Moya+RxSwift.swift
- README.md
- Moya.podspec
- etc...
```

Thoughts?

**Comment by alcarvalho** [comment]
:+1:
Would also put MoyaResponse file inside a newly created ReactiveCore
folder.

**Comment by aschuch** [comment]
Is `MoyaResponse` solely used for ReactiveCocoa stuff? If so, we should document that in its header too.

**Comment by alcarvalho** [comment]
No, it's used by reactive in general, meaning ReactiveCocoa and RxSwift, right now. I have extracted it from the ReactiveCocoa integration when I implemented the RxSwift provider to be a common core.

**Comment by SRandazzo** [comment]
I am also :+1: for this!

On a related note, is there not a dedicated XCProj/workspace for Moya development?
If we have one, we can mirror project structure with file structure

**Comment by alcarvalho** [comment]
@SRandazzo the lack of the xcproj is strange to me too. The way I do it here is by opening the Demo to edit the code for the library. Not the most intuitive.

**Comment by ashfurrow** [comment]
I like this idea – will do. 

As for a dedicated project/workspace, what would be the advantages of using one? The library is installed using CocoaPods; the Demo project is for illustrating the library's use and for its unit tests. That could be moved into a test-only project, sure. What advantages would there be of having another project/workspace?
