### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Moya#149]
Is this ready for release? It's a 2.0 because of semantic versioning (we have breaking changes). The remaining issues are all long-term goals and most should be doable without breaking things. 

Anyone have feels about this?

**Comment by alcarvalho** [comment]
One thing we could fix before the release are the versions to which we depend on CocoaPods to support sane updates on them like mentioned on #153. I have also checked that if we update all the pods of the Demo project we fetch the version 0.4.0 of Quick that won't compile with Swift 1.2.

**Comment by alcarvalho** [comment]
I just found a problem with cocoapods versioning, though.

If we add the `~>` to ReactiveCocoa, when we run a `pod update` on the Demo project it downgrades to alpha version:

`Installing ReactiveCocoa 3.0.0-alpha.1 (was 3.0-beta.6)`

**Comment by ashfurrow** [comment]
Hmm. So running `pod update` isn't really something that should be done frequently; I can't remember the last time I ran it. Running `pod install` instead looks at the Podfile.lock file to see what specific versions need to be used. Does that make sense?

**Comment by alcarvalho** [comment]
Yeah, but the intent here was to update the pods, really. I don't know if that should be done on a library regularly. I did it also to test if everything still works with the latest versions of the libraries that we should support.

**Comment by ashfurrow** [comment]
For sure, but Quick 0.4.0 uses Swift 2, as I understand it, which Moya does not yet.

**Comment by alcarvalho** [comment]
Yeah, that's why I have restricted it to 0.3.x in here #157

**Comment by ashfurrow** [comment]
OK, so this looks ready. Once #174 fixes CI, I'll release a 2.0 :tada:

**Comment by ashfurrow** [comment]
Also pushed to @CocoaPods trunk: https://raw.githubusercontent.com/CocoaPods/Specs/27abd436816cd75b5fa76230c1c325d7810467dc/Specs/Moya/2.0.0/Moya.podspec.json
