### ISSUE TITLE
Alamofire.Request as returned type of provider.request(.Zen)

### ISSUE THREAD

**Issue by XBeg9** [ashfurrow/Moya#155]
I am trying to find out how to get `Alamofire.Request` after I did `provider.request(.Zen)` (currently it responses with `Cancellable` protocol).

```swift
func sendRequest(request: NSURLRequest, completion: MoyaCompletion) -> CancellableToken {

        networkActivityClosure?(change: .Began)

        // We need to keep a reference to the closure without a reference to ourself.
        let networkActivityCallback = networkActivityClosure
        let request = Alamofire.Manager.sharedInstance.request(request)
            .response { (request: NSURLRequest, response: NSHTTPURLResponse?, data: AnyObject?, error: NSError?) -> () in
                networkActivityCallback?(change: .Ended)

                // Alamofire always sends the data param as an NSData? type, but we'll
                // add a check just in case something changes in the future.
                let statusCode = response?.statusCode
                if let data = data as? NSData {
                    completion(data: data, statusCode: statusCode, response:response, error: error)
                } else {
                    completion(data: nil, statusCode: statusCode, response:response, error: error)
                }
        }

        return CancellableToken {
            request.cancel()
        }
    }
```
I think it's more needed to return `Request` here then CancellableToken or merge this somehow. What do you think?

**Comment by XBeg9** [comment]
For example I am not using `Moya` for now, because I want to use https://github.com/tristanhimmelman/AlamofireObjectMapper

**Comment by ashfurrow** [comment]
Hi there @XBeg9 – good question. The `request` function purposefully returns a `CancellableToken` to obscure the underlying Alamofire implementation. The idea is that you shouldn't need to know that Moya uses Alamofire "under the hood", so returning the request defeats that purpose. 

So, how do we make it so you can use this mapping library, which looks pretty cool. That library is actually a thin wrapper around [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper), which you could use directly. That's not a satisfying answer, I know. 

An alternative would be to extend the `MoyaProvider` in another subspec in a similar way that AlamofireObjectMapper does. It shouldn't be that much work, but I'm swamped until the weekend.

What sounds like the best solution to you? Does anyone else have suggestions?

**Comment by XBeg9** [comment]
@ashfurrow hi Ash, glad to see you here :) Just checked https://github.com/tristanhimmelman/AlamofireObjectMapper/blob/master/AlamofireObjectMapper/AlmofireObjectMapper.swift and they use `extension Request`. How I can similar with `MoyaProvider`?

**Comment by ashfurrow** [comment]
So I'm thinking that we'd have `extension MoyaProvider` that would call through to the original `Request`, but also take a callback block similar to AlamofireObjectMapper. So it would call through to the original `request` function, then do something in the callback to map the objects, then call its own callback. 

So it would look something roughly like this:

```
func someRequest(target, someCallback) {
    request(target) { (thing) -> () in
        let mappedObject = ObjectMapperCallOrWhatever
        someCallback(mappedObject)
    }
}
```

Does that make sense?

**Comment by XBeg9** [comment]
@ashfurrow Thanks, already found solution. Inspired by Kiosk app :)

```swift
public class Provider<T where T: MoyaTarget>: MoyaProvider<T> {

    override public init(endpointsClosure: MoyaEndpointsClosure = MoyaProvider.DefaultEndpointMapping(), endpointResolver: MoyaEndpointResolution = MoyaProvider.DefaultEnpointResolution(), stubResponses: Bool = false, stubBehavior: MoyaStubbedBehavior = MoyaProvider.DefaultStubBehavior, networkActivityClosure: Moya.NetworkActivityClosure? = nil) {
        super.init(endpointsClosure: endpointsClosure, endpointResolver: endpointResolver, stubResponses: stubResponses, stubBehavior: stubBehavior, networkActivityClosure: networkActivityClosure)
    }
    
    public func mappingRequest(token: T) -> Request {
        let endpoint = self.endpoint(token)
        let request = endpointResolver(endpoint: endpoint)
        
        return sendRequest(request)
    }
}

private extension Provider {
    func sendRequest(request: NSURLRequest) -> Request {
        return Alamofire.Manager.sharedInstance.request(request)
    }
}
```

And then somewhere in the code:
```swift
APIProvider.mappingRequest(.Login(username: "test", password: "test123")).responseObject { (user: User?, error: NSError?) -> Void in
            println(user?.username)
}
```
