### ISSUE TITLE
Moya Carthage: RxSwift not included

### ISSUE THREAD

**Issue by aschuch** [ashfurrow/Moya#159]
When installing Moya (master) using Carthage, I am running into the following error on app launch:

```
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: [REDACTED]/Frameworks/Moya.framework/Moya
  Reason: image not found
```

Seems like RxSwift is not downloaded, thus not found at app launch. 
I have tried to add RxSwift to the Cartfile but [RxSwift does not yet support Carthage](https://github.com/kzaher/RxSwift/issues/40).

/cc @neonichu

**Comment by ashfurrow** [comment]
Hmm. I'm not quite sure what to make of this. Hoping @neonichu knows.

**Comment by ashfurrow** [comment]
I'm going to move this to #154 – there's a discussion there surrounding Moya and Carthage.
