### ISSUE TITLE
MoyaResponse is crashing when used with ReactiveCocoa

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Moya#78]
I get a warning like:

```
NSForwarding: warning: object 0x7f8943920a10 of class 'Kiosk.MoyaResponse' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector
```

**Comment by aschuch** [comment]
I just had the same issue and resolved it with your suggested fix.
Is there a reason this has not made it into master yet? Do you want to hold off until this is resolved in ReactiveCocoa itself?

**Comment by ashfurrow** [comment]
To be honest, I've been really busy. I'd gladly merge a pull request, though.

**Comment by aschuch** [comment]
:+1: done
