### ISSUE TITLE
Distribute to AppStore

### ISSUE THREAD

**Issue by retsohuang** [ashfurrow/Moya#88]
I use this framework with CocoaPods, but I can't install my app on my device via OTA install (use Fabric).

And I try to submit to iTunes Connect, I got this message.

```
Dear developer,

We have discovered one or more issues with your recent delivery for "". To process your delivery, the following issues must be corrected:

This bundle is invalid - The file extension must be .zip.
```

Any idea?

**Comment by ashfurrow** [comment]
Should be done now. Please reopen if not.
