### ISSUE TITLE
Custom ParameterEncodings

### ISSUE THREAD

**Issue by chipsterm** [ashfurrow/Moya#90]
I have been working with this framework on iOS and am having a compile issue when adding custom parameterEncodings. I was wondering if you could help me out. 

My EyeQEndPoints enum does not implement URLRequestConvertible which I believe is ok. 

I declare the custom closure as follows:

let xmlParameterEncoding:(URLRequestConvertible, [String: AnyObject]?) -> (NSURLRequest, NSError?) = {(URLRequest, parameters) in {

//this is just to get things working
return (NSURLRequest.URLRequest, nil)
}

In the endpointsClosure, I set the custom closure:

let endpointsClosure = { (target: EyeQEndPoints, method: Moya.Method, parameters: [String: AnyObject]) -> Endpoint<EyeQEndPoints> in
    return Endpoint<EyeQEndPoints>(URL: url(target), sampleResponse: EndpointSampleResponse.Success(200, target.sampleData), method: method, parameters: parameters, parameterEncoding: .Custom(xmlParameterEncoding))
}

The compiler throws an error on .Custom(xmlParameterEncoding) of

error: type 'URLRequestConvertible' does not conform to protocol 'URLRequestConvertible'
    return Endpoint<EyeQEndPoints>(URL: url(target), sampleResponse: EndpointSampleResponse.Success(200, target.sampleData), method: method, parameters: parameters, parameterEncoding: .Custom(xmlParameterEncoding))

Thanks for your help.

**Comment by chipsterm** [comment]
Thank you for the response. I figured that out shortly after I created the ticket.

**Comment by ashfurrow** [comment]
Awesome! I'll close this. Feel free to reopen or open a new issue if you have other questions.
