### ISSUE TITLE
Delay in stubs

### ISSUE THREAD

**Issue by swizzlr** [ashfurrow/Moya#95]
It would be sweet if there were a way to randomly or deterministically add a short delay to stub request returns to make it a little more "real".

**Comment by ashfurrow** [comment]
I can see the value in making sure that the network code is run asynchronously, but tying your network callbacks to the assumption that they'll have a short, undetermined delay is probably not the best practice to be encouraging. 

So maybe not a delay, but some kind of mechanism to defer to the next invocation of the runloop?

**Comment by swizzlr** [comment]
Oh, this is purely so we can show off a loading animation.

**Comment by ashfurrow** [comment]
Very good point – I hadn't considered stubs much outside a testing context. This is a great idea. I'll look into it more.

**Comment by swizzlr** [comment]
Super helpful for when stage/dev is down.

**Comment by ashfurrow** [comment]
Yeah, we stub responses based on a heuristic to check if you have access to the API or not. I can also see it being valuable in rapid application prototyping, where the API isn't ready or stable yet. Thinking of adding a(n optional?) property to the enum protocol that allows developers to specify a delay. Thoughts?

**Comment by orta** [comment]
IMO cool, as long as 0 doesn't jump out of being synchronous

**Comment by ashfurrow** [comment]
We can use an enum with associated values. Something like:

```swft
enum StubBehavior {
    case .Immediate
    case .Delay(seconds: Int)
}
```

**Comment by orta** [comment]
:+1:
